package icu.thyself.cloudlesson.mapper;

import icu.thyself.cloudlesson.model.Attention;
import icu.thyself.cloudlesson.model.AttentionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    long countByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int deleteByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int insert(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int insertSelective(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    List<Attention> selectByExample(AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    Attention selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Attention record, @Param("example") AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByExample(@Param("record") Attention record, @Param("example") AttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByPrimaryKeySelective(Attention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByPrimaryKey(Attention record);
}