package icu.thyself.cloudlesson.mapper;

import icu.thyself.cloudlesson.model.AuthorApply;
import icu.thyself.cloudlesson.model.AuthorApplyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AuthorApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    long countByExample(AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int deleteByExample(AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int insert(AuthorApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int insertSelective(AuthorApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    List<AuthorApply> selectByExampleWithBLOBs(AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    List<AuthorApply> selectByExample(AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    AuthorApply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") AuthorApply record, @Param("example") AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") AuthorApply record, @Param("example") AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByExample(@Param("record") AuthorApply record, @Param("example") AuthorApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByPrimaryKeySelective(AuthorApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(AuthorApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    int updateByPrimaryKey(AuthorApply record);
}