package icu.thyself.cloudlesson.mapper;

import icu.thyself.cloudlesson.model.MailCheck;
import icu.thyself.cloudlesson.model.MailCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MailCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    long countByExample(MailCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int deleteByExample(MailCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int insert(MailCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int insertSelective(MailCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    List<MailCheck> selectByExample(MailCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    MailCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") MailCheck record, @Param("example") MailCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByExample(@Param("record") MailCheck record, @Param("example") MailCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByPrimaryKeySelective(MailCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    int updateByPrimaryKey(MailCheck record);
}