package icu.thyself.cloudlesson.mapper;

import icu.thyself.cloudlesson.model.Recommend;
import icu.thyself.cloudlesson.model.RecommendExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    long countByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int deleteByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    List<Recommend> selectByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    Recommend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int updateByExample(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu May 14 17:27:42 CST 2020
     */
    int updateByPrimaryKey(Recommend record);
}