package icu.thyself.cloudlesson.model;

import java.io.Serializable;

public class Attention implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.topic_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attention
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.id
     *
     * @return the value of attention.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.id
     *
     * @param id the value for attention.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.account_id
     *
     * @return the value of attention.account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.account_id
     *
     * @param accountId the value for attention.account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.topic_id
     *
     * @return the value of attention.topic_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.topic_id
     *
     * @param topicId the value for attention.topic_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.gmt_create
     *
     * @return the value of attention.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.gmt_create
     *
     * @param gmtCreate the value for attention.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}