package icu.thyself.cloudlesson.model;

import java.io.Serializable;

public class AuthorApply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table author_apply
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author_apply.id
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author_apply.account_id
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private Long accountId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author_apply.gmt_create
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private Long gmtCreate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author_apply.status
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author_apply.apply_reason
     *
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    private String applyReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author_apply.id
     *
     * @return the value of author_apply.id
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author_apply.id
     *
     * @param id the value for author_apply.id
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author_apply.account_id
     *
     * @return the value of author_apply.account_id
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author_apply.account_id
     *
     * @param accountId the value for author_apply.account_id
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author_apply.gmt_create
     *
     * @return the value of author_apply.gmt_create
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author_apply.gmt_create
     *
     * @param gmtCreate the value for author_apply.gmt_create
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author_apply.status
     *
     * @return the value of author_apply.status
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author_apply.status
     *
     * @param status the value for author_apply.status
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author_apply.apply_reason
     *
     * @return the value of author_apply.apply_reason
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public String getApplyReason() {
        return applyReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author_apply.apply_reason
     *
     * @param applyReason the value for author_apply.apply_reason
     * @mbg.generated Sat May 16 16:54:35 CST 2020
     */
    public void setApplyReason(String applyReason) {
        this.applyReason = applyReason == null ? null : applyReason.trim();
    }
}