package icu.thyself.cloudlesson.model;

import java.io.Serializable;

public class MailCheck implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_check.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_check.captcha
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private String captcha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mail_check
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_check.id
     *
     * @return the value of mail_check.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_check.id
     *
     * @param id the value for mail_check.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_check.captcha
     *
     * @return the value of mail_check.captcha
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public String getCaptcha() {
        return captcha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_check.captcha
     *
     * @param captcha the value for mail_check.captcha
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setCaptcha(String captcha) {
        this.captcha = captcha == null ? null : captcha.trim();
    }
}