package icu.thyself.cloudlesson.model;

import java.io.Serializable;

public class Post implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.author
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.tags
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.gmt_create
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.gmt_modify
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.gmt_recent
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long gmtRecent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.recent_reply_account_id
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Long recentReplyAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.view_count
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.reply_count
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private Integer replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.video_link
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private String videoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.author
     *
     * @return the value of post.author
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.author
     *
     * @param author the value for post.author
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setAuthor(Long author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.tags
     *
     * @return the value of post.tags
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.tags
     *
     * @param tags the value for post.tags
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.gmt_create
     *
     * @return the value of post.gmt_create
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.gmt_create
     *
     * @param gmtCreate the value for post.gmt_create
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.gmt_modify
     *
     * @return the value of post.gmt_modify
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.gmt_modify
     *
     * @param gmtModify the value for post.gmt_modify
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.gmt_recent
     *
     * @return the value of post.gmt_recent
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getGmtRecent() {
        return gmtRecent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.gmt_recent
     *
     * @param gmtRecent the value for post.gmt_recent
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setGmtRecent(Long gmtRecent) {
        this.gmtRecent = gmtRecent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.recent_reply_account_id
     *
     * @return the value of post.recent_reply_account_id
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Long getRecentReplyAccountId() {
        return recentReplyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.recent_reply_account_id
     *
     * @param recentReplyAccountId the value for post.recent_reply_account_id
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setRecentReplyAccountId(Long recentReplyAccountId) {
        this.recentReplyAccountId = recentReplyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.view_count
     *
     * @return the value of post.view_count
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.view_count
     *
     * @param viewCount the value for post.view_count
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.reply_count
     *
     * @return the value of post.reply_count
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.reply_count
     *
     * @param replyCount the value for post.reply_count
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.video_link
     *
     * @return the value of post.video_link
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.video_link
     *
     * @param videoLink the value for post.video_link
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     * @mbg.generated Tue May 05 22:05:32 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}