package icu.thyself.cloudlesson.model;

import java.io.Serializable;

public class Topic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.author
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.tags
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_modify
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_recent
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long gmtRecent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.recent_reply_account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Long recentReplyAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.view_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.reply_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private Integer replyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.video_link
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private String videoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.author
     *
     * @return the value of topic.author
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.author
     *
     * @param author the value for topic.author
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setAuthor(Long author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.tags
     *
     * @return the value of topic.tags
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.tags
     *
     * @param tags the value for topic.tags
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_create
     *
     * @return the value of topic.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_create
     *
     * @param gmtCreate the value for topic.gmt_create
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_modify
     *
     * @return the value of topic.gmt_modify
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_modify
     *
     * @param gmtModify the value for topic.gmt_modify
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_recent
     *
     * @return the value of topic.gmt_recent
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getGmtRecent() {
        return gmtRecent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_recent
     *
     * @param gmtRecent the value for topic.gmt_recent
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setGmtRecent(Long gmtRecent) {
        this.gmtRecent = gmtRecent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.recent_reply_account_id
     *
     * @return the value of topic.recent_reply_account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Long getRecentReplyAccountId() {
        return recentReplyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.recent_reply_account_id
     *
     * @param recentReplyAccountId the value for topic.recent_reply_account_id
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setRecentReplyAccountId(Long recentReplyAccountId) {
        this.recentReplyAccountId = recentReplyAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.view_count
     *
     * @return the value of topic.view_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.view_count
     *
     * @param viewCount the value for topic.view_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.reply_count
     *
     * @return the value of topic.reply_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public Integer getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.reply_count
     *
     * @param replyCount the value for topic.reply_count
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setReplyCount(Integer replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.video_link
     *
     * @return the value of topic.video_link
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.video_link
     *
     * @param videoLink the value for topic.video_link
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated Thu May 07 21:15:11 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}